version: 2
updates:
  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Lua/LuaRocks dependencies (if you add a rockspec file)
  # - package-ecosystem: "bundler"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
  #     - "lua"
