-- Tests for markdown-plus footnotes line_parser sub-module
describe("markdown-plus footnotes line_parser", function()
  local line_parser = require("markdown-plus.footnotes.line_parser")
  local parser = require("markdown-plus.footnotes.parser")

  describe("patterns", function()
    it("exports expected pattern keys", function()
      assert.is_not_nil(line_parser.patterns.reference)
      assert.is_not_nil(line_parser.patterns.definition)
      assert.is_not_nil(line_parser.patterns.continuation)
      assert.is_not_nil(line_parser.patterns.section_header)
    end)

    it("matches through parser facade", function()
      assert.equals(line_parser.patterns.reference, parser.patterns.reference)
      assert.equals(line_parser.patterns.definition, parser.patterns.definition)
    end)
  end)

  describe("find_references_in_line", function()
    it("finds single reference", function()
      local refs = line_parser.find_references_in_line("Text[^1] here.")
      assert.equals(1, #refs)
      assert.equals("1", refs[1].id)
      assert.equals(5, refs[1].start_col)
      assert.equals(8, refs[1].end_col)
    end)

    it("finds multiple references", function()
      local refs = line_parser.find_references_in_line("A[^1] and B[^2].")
      assert.equals(2, #refs)
      assert.equals("1", refs[1].id)
      assert.equals("2", refs[2].id)
    end)

    it("includes line_num when provided", function()
      local refs = line_parser.find_references_in_line("Text[^1].", 42)
      assert.equals(42, refs[1].line_num)
    end)

    it("defaults line_num to 0", function()
      local refs = line_parser.find_references_in_line("Text[^1].")
      assert.equals(0, refs[1].line_num)
    end)

    it("skips references inside inline code", function()
      local refs = line_parser.find_references_in_line("Real[^1] and `code [^fake]` here.")
      assert.equals(1, #refs)
      assert.equals("1", refs[1].id)
    end)

    it("skips references inside double backtick code", function()
      local refs = line_parser.find_references_in_line("Real[^1] and ``code [^fake]`` here.")
      assert.equals(1, #refs)
      assert.equals("1", refs[1].id)
    end)

    it("excludes definition patterns", function()
      local refs = line_parser.find_references_in_line("[^1]: This is a definition")
      assert.equals(0, #refs)
    end)

    it("returns empty for plain text", function()
      local refs = line_parser.find_references_in_line("No footnotes here.")
      assert.equals(0, #refs)
    end)

    it("handles hyphen and underscore IDs", function()
      local refs = line_parser.find_references_in_line("Text[^my-note_1] here.")
      assert.equals(1, #refs)
      assert.equals("my-note_1", refs[1].id)
    end)
  end)

  describe("parse_reference_at_cursor", function()
    it("returns reference when cursor is on it", function()
      local ref = line_parser.parse_reference_at_cursor("Text[^1] here.", 6)
      assert.is_not_nil(ref)
      assert.equals("1", ref.id)
    end)

    it("returns nil when cursor is outside reference", function()
      local ref = line_parser.parse_reference_at_cursor("Text[^1] here.", 1)
      assert.is_nil(ref)
    end)

    it("works through parser facade", function()
      local ref = parser.parse_reference_at_cursor("Text[^1] here.", 6)
      assert.is_not_nil(ref)
      assert.equals("1", ref.id)
    end)
  end)

  describe("parse_definition", function()
    it("parses valid definition", function()
      local def = line_parser.parse_definition("[^1]: Content here.")
      assert.is_not_nil(def)
      assert.equals("1", def.id)
      assert.equals("Content here.", def.content)
    end)

    it("parses definition with leading whitespace", function()
      local def = line_parser.parse_definition("  [^1]: Indented.")
      assert.is_not_nil(def)
      assert.equals("1", def.id)
    end)

    it("returns nil for non-definition", function()
      local def = line_parser.parse_definition("Regular text.")
      assert.is_nil(def)
    end)

    it("parses empty content", function()
      local def = line_parser.parse_definition("[^1]:")
      assert.is_not_nil(def)
      assert.equals("1", def.id)
      assert.equals("", def.content)
    end)

    it("works through parser facade", function()
      local def = parser.parse_definition("[^test]: Hello.")
      assert.is_not_nil(def)
      assert.equals("test", def.id)
    end)
  end)

  describe("is_continuation_line", function()
    it("detects 4-space indented line", function()
      local is_cont, content = line_parser.is_continuation_line("    Continued text.")
      assert.is_true(is_cont)
      assert.equals("Continued text.", content)
    end)

    it("detects tab-indented line", function()
      local is_cont, content = line_parser.is_continuation_line("\tTab text.")
      assert.is_true(is_cont)
      assert.equals("Tab text.", content)
    end)

    it("rejects empty line", function()
      local is_cont, content = line_parser.is_continuation_line("")
      assert.is_false(is_cont)
      assert.is_nil(content)
    end)

    it("rejects unindented line", function()
      local is_cont, content = line_parser.is_continuation_line("No indent.")
      assert.is_false(is_cont)
      assert.is_nil(content)
    end)

    it("works through parser facade", function()
      local is_cont, _ = parser.is_continuation_line("    Continued.")
      assert.is_true(is_cont)
    end)
  end)
end)
