---Test suite for markdown-plus.nvim header manipulation
---Tests promote, demote, set_header_level, and toggle_atx_setext functions
---@diagnostic disable: undefined-field
local helpers = require("spec.helpers")
local manip = require("markdown-plus.headers.manipulation")

describe("markdown-plus headers manipulation", function()
  local notify_spy

  before_each(function()
    helpers.create_buf({ "" })
    notify_spy = helpers.mocks.mock_notify()
  end)

  after_each(function()
    notify_spy.restore()
    helpers.destroy_buf()
  end)

  describe("promote_header", function()
    it("promotes ATX H3 to H2", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "### My Header" })
      helpers.set_cursor(1, 0)
      manip.promote_header()
      local lines = helpers.buf_lines()
      assert.are.equal("## My Header", lines[1])
    end)

    it("notifies at H1 boundary", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "# Already H1" })
      helpers.set_cursor(1, 0)
      manip.promote_header()
      assert.are.equal(1, #notify_spy.calls)
      assert.are.equal("Already at highest level (H1)", notify_spy.calls[1].msg)
    end)
  end)

  describe("demote_header", function()
    it("demotes ATX H2 to H3", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "## My Header" })
      helpers.set_cursor(1, 0)
      manip.demote_header()
      local lines = helpers.buf_lines()
      assert.are.equal("### My Header", lines[1])
    end)

    it("notifies at H6 boundary", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "###### H6 Header" })
      helpers.set_cursor(1, 0)
      manip.demote_header()
      assert.are.equal(1, #notify_spy.calls)
      assert.are.equal("Already at lowest level (H6)", notify_spy.calls[1].msg)
    end)
  end)

  describe("set_header_level", function()
    it("converts plain text to header", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "Plain text" })
      helpers.set_cursor(1, 0)
      manip.set_header_level(2)
      local lines = helpers.buf_lines()
      assert.are.equal("## Plain text", lines[1])
    end)

    it("changes existing header level", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "### Old Header" })
      helpers.set_cursor(1, 0)
      manip.set_header_level(1)
      local lines = helpers.buf_lines()
      assert.are.equal("# Old Header", lines[1])
    end)

    it("notifies on invalid level 0", function()
      helpers.set_cursor(1, 0)
      manip.set_header_level(0)
      assert.are.equal(1, #notify_spy.calls)
      assert.are.equal(vim.log.levels.ERROR, notify_spy.calls[1].level)
    end)

    it("notifies on empty line", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "" })
      helpers.set_cursor(1, 0)
      manip.set_header_level(1)
      assert.are.equal(1, #notify_spy.calls)
      assert.are.equal("Cannot create header from empty line", notify_spy.calls[1].msg)
    end)
  end)

  describe("toggle_atx_setext", function()
    it("converts ATX H1 to setext", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "# My Title" })
      helpers.set_cursor(1, 0)
      manip.toggle_atx_setext()
      local lines = helpers.buf_lines()
      assert.are.equal("My Title", lines[1])
      assert.is_truthy(lines[2]:match("^=+$"))
    end)

    it("warns when toggling H3+ to setext", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "### Deep Header" })
      helpers.set_cursor(1, 0)
      manip.toggle_atx_setext()
      assert.are.equal(1, #notify_spy.calls)
      assert.are.equal("Only H1/H2 can be converted to setext style", notify_spy.calls[1].msg)
      assert.are.equal(vim.log.levels.WARN, notify_spy.calls[1].level)
    end)
  end)
end)
